# Argon OS — fstab generation
---
mountOptions:
  default: defaults,noatime
  btrfs: defaults,noatime,compress=zstd
  btrfs_swap: defaults,noatime

ssdExtraMountOptions:
  ext4: discard
  btrfs: discard=async

crypttabOptions: luks,discard
