# Argon OS — user creation
---
defaultGroups:
  - name: users
  - name: sudo
  - name: netdev
  - name: audio
  - name: video
  - name: plugdev
  - name: cdrom

autologinGroup: autologin
# Privacy/security posture: no autologin, no root account, sudo for admin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false

passwordRequirements:
  minLength: 8
  maxLength: -1

allowWeakPasswords: false
allowWeakPasswordsDefault: false

userShell: /bin/bash
